### ISSUE TITLE
Feature request: Slot

### ISSUE THREAD

**Issue by jmealo** [kamilwylegala/vue-tournament-bracket#16]
Great component!

Would it be possible to add a slot instead so we could pass in an image or something else in place of text?

Thanks!

**Comment by kamilwylegala** [comment]
Hey @jmealo 

But currently scope is supported?
```
<template slot="player" slot-scope="{{ player }}">
            {{ player.name }}
</template>
```

Could you elaborate a bit what is needed exactly?

**Comment by kamilwylegala** [comment]
No feedback, closing.
