### ISSUE TITLE
Nuxt.js support with vue 2

### ISSUE THREAD

**Issue by duongthaison98** [kamilwylegala/vue-tournament-bracket#26]
Hello.
Can you show me how to use it in Nuxt.js project. When I imported in page, it shows error "document is not defined". I think which cause the problem was Nuxt.js is server-side rendering library.
vue: "2.6.14"
nuxt: "2.15.8"
Thanks

**Comment by BlackYuzia** [comment]
DId you try only client render? @duongthaison98

**Comment by duongthaison98** [comment]
> Did you try only client render? @duongthaison98 error about document usual means what this can't work in SSR mode.

yes i did. i put <client-only></client-only> wrap outside <bracket></bracket> but its still not working

**Comment by BlackYuzia** [comment]
> > Did you try only client render? @duongthaison98 error about document usual means what this can't work in SSR mode.
> 
> yes i did. i put wrap outside but its still not working

How you load this lib? By plugin on client side?

**Comment by duongthaison98** [comment]
> > > Did you try only client render? @duongthaison98 error about document usual means what this can't work in SSR mode.
> > 
> > 
> > yes i did. i put wrap outside but its still not working
> 
> How you load this lib? By plugin on client side?

i loaded by plugin on client side. the problem 'document is not defined' is solved but new come up was '[Vue warn]: Unknown custom element: <bracket> - did you register the component correctly? For recursive components, make sure to provide the "name" option.'

**Comment by BlackYuzia** [comment]
> i loaded by plugin on client side. the problem 'document is not defined' is solved but new come up was '[Vue warn]: Unknown custom element: - did you register the component correctly? For recursive components, make sure to provide the "name" option.'

Suppose
1. You already have a component with that name.
2. You didn't register your component.

**Comment by duongthaison98** [comment]
> > i loaded by plugin on client side. the problem 'document is not defined' is solved but new come up was '[Vue warn]: Unknown custom element: - did you register the component correctly? For recursive components, make sure to provide the "name" option.'
> 
> Suppose
> 
> 1. You already have a component with that name.
> 2. You didn't register your component.

i registered like this: 
`import Vue from 'vue';
import Bracket from "vue-tournament-bracket";

Vue.use(Bracket);
Vue.component("vue-tournament-bracket", Bracket);` 

is it correct ?

**Comment by BlackYuzia** [comment]
Show your code of plugin

**Comment by duongthaison98** [comment]
> Show full code of your plugin


vue-tournament-bracket.js (plugin)
`import Vue from 'vue';
import Bracket from "vue-tournament-bracket";

Vue.use(Bracket);
Vue.component("vue-tournament-bracket", Bracket);`

nuxt.config.js
`plugins: [
    {
      src: '~/plugins/vue-tournament-bracket',
      ssr: false
    },
  ],`

**Comment by BlackYuzia** [comment]
Looks right, show how do you use this component

**Comment by duongthaison98** [comment]
> Looks right, show how do you use this component

`<client-only>
          <bracket :rounds="rounds">
            <template slot="player" slot-scope="{ player }">
              {{ player.name }}
            </template>
          </bracket>
        </client-only>`

`<script>
const rounds = [
        //Semi finals
        {
            games: [
                {
                    player1: { id: "1", name: "Competitor 1", winner: false },
                    player2: { id: "4", name: "Competitor 4", winner: true },
                },
                {
                    player1: { id: "5", name: "Competitor 5", winner: false },
                    player2: { id: "8", name: "Competitor 8", winner: true },
                }
            ]
        },
        //Final
        {
            games: [
                {
                    player1: { id: "4", name: "Competitor 4", winner: false },
                    player2: { id: "8", name: "Competitor 8", winner: true },
                }
            ]
        }
    ];
export default {
  data() {
    return {
      rounds: rounds,
    }
   }
}
</script>`

**Comment by BlackYuzia** [comment]
try `vue-tournament-bracket` instead of `bracket`, you register `vue-tournament-bracket` not a `bracket`.
